version: 1.2.0-{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  publish_nuget: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: KiU+IxCEHz91ElWv3YAXol9R51VF1+dUvcxrn/ZGlWPeu/oqlGKaDrE5fi9SPsJ+
  on:
    branch: release