version: 3.0.10.1-{build}

before_build:
  - nuget restore

build:
  publish_nuget: true
  verbosity: minimal

configuration: Release

deploy:
- provider: NuGet
  api_key:
    secure: KiU+IxCEHz91ElWv3YAXol9R51VF1+dUvcxrn/ZGlWPeu/oqlGKaDrE5fi9SPsJ+
  on:
    branch: release